name: tier test 

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Plugin
        run: mvn clean package

      # ⭐ THIS PART WAS MISSING
      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: AlphaAntiCheat
          path: target/*.jar
          
